shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings, yaml/plain-scalar
trustPolicy: "off"

packages:
  - "packages/*"
  - "tools/*"

overrides:
  lightningcss: 1.30.1

catalog:
  "@antfu/eslint-config": ^7.7.3
  "@better-auth/expo": 1.6.11
  "@t3-oss/env-core": ^0.13.11
  "@trpc/server": ^11.17.0
  "@types/node": ^22.19.20
  better-auth: 1.6.11
  eslint: ^9.39.4
  eslint-plugin-format: ^2.0.1
  superjson: ^2.2.6
  typescript: ^5.9.3
  zod: ^4.4.3

allowBuilds:
  esbuild: true
